name: build

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: DotnetVersion
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: restore
        run: dotnet restore

      - name: Builds
        run: dotnet build --configuration Release --no-restore
        
      - name: Test
        run: dotnet test --no-restore
