name: Lint

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Markdown

    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: Lint
        uses: nosborn/github-action-markdown-cli@v1.1.1
        with:
          files: "**/*.md"
