name: release

on:
  release:
    types:
      - created

jobs:
  release:
    name: release
    timeout-minutes: 5
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: DotnetVersion
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack AprsSharp.AprsParser
        run: dotnet pack src/AprsParser/AprsParser.csproj --configuration Release --no-build

      - name: Pack AprsSharp.AprsIsClient
        run: dotnet pack src/AprsIsClient/AprsIsClient.csproj --configuration Release --no-build

      - name: Pack AprsSharp.KissTnc
        run: dotnet pack src/KissTnc/KissTnc.csproj --configuration Release --no-build

      - name: Pack AprsSharp.Shared
        run: dotnet pack src/Shared/Shared.csproj --configuration Release --no-build

      - name: Publish AprsSharp.AprsParser
        run: dotnet nuget push src/AprsParser/bin/Release/AprsSharp.AprsParser.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      - name: Publish AprsSharp.AprsIsClient
        run: dotnet nuget push src/AprsIsClient/bin/Release/AprsSharp.AprsIsClient.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      - name: Publish AprsSharp.KissTnc
        run: dotnet nuget push src/KissTnc/bin/Release/AprsSharp.KissTnc.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      - name: Publish AprsSharp.Shared
        run: dotnet nuget push src/Shared/bin/Release/AprsSharp.Shared.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
