name: build

on:
  release:
    types:
      - created

jobs:
  build:
    name: build
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v2

      - name: DotnetVersion
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --configuration Release --no-build

      - name: Pack AprsSharp.AprsParser
        run: dotnet pack src/AprsParser/AprsParser.csproj --configuration Release --no-build

      - name: Pack AprsSharp.AprsIsClient
        run: dotnet pack src/AprsIsConnection/AprsIsConnection.csproj --configuration Release --no-build

      - name: Publish AprsShar.AprsParser
        run: dotnet nuget push src/AprsParser/bin/Release/AprsSharp.AprsParser.*.nupkg --api-key $NUGET_API_KEY

      - name: Publish AprsShar.AprsIsClient
        run: dotnet nuget push src/AprsIsConnection/bin/Release/AprsSharp.AprsIsClient.*.nupkg --api-key $NUGET_API_KEY
